apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: forge-authentication-aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: forge-authentication-creds-sec
      type: Opaque
      data:
        - objectName: "forge-authentication-sec-alias"
          key: forge-authentication-creds

  parameters:
    objects: |
        - objectName: "/app/forge-authentication-api/dev"
          objectType: "secretsmanager"  
          objectAlias: "forge-authentication-sec-alias"
          objectVersionLabel: "AWSCURRENT"
