apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forge-authentication-develop
  namespace: argocd
spec:
  project: sop-develop
  source:
    repoURL: 'https://github.com/Simple-Online-Healthcare/forge_k8s_manifests.git'
    path: deployments/apps/forge_authentication
    targetRevision: deploy-develop
    directory:
      recurse: false
      jsonnet: {}
  destination:
    namespace: forge-authentication-develop
    name: eks-forge-dev-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true    
    syncOptions:
      - CreateNamespace=true
