apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forge-authentication-develop

commonLabels:
  customer: forge-authentication-develop
resources:
- sec.yaml
- api-aws-sec.yaml
- hpa.yaml
- configmap.yaml
- ingress.yaml
- ../../../base/apps/forge_authentication

patchesStrategicMerge:
- deploy.yaml

images:
- name: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/forge-authentication-develop
  newTag: '1'
