apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saleor-backend-staging

commonLabels:
  customer: saleor-backend-staging
resources:
- redis-sec.yaml
- sec.yaml
- api-aws-sec.yaml
- hpa.yaml
- configmap.yaml
- ingress.yaml
- ../../../base/apps/soh-backend

patchesStrategicMerge:
- deploy.yaml

images:
- name: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/saleor-backend-staging
  newTag: '25'
