apiVersion: v1
kind: PersistentVolume
metadata:
  name: stripe-pv
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: efs-sc-qa
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e3d03e7bd9703fc2
