apiVersion: v1
kind: Service
metadata:
  name: saleor-payment-qa
  labels:
    app: saleor-payment-qa
spec:
  type: ClusterIP
  ports:
  - name: http-saleor
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: saleor-payment-qa
