apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forge-patient-frontend-develop

commonLabels:
  customer: forge-patient-frontend-develop
resources:
- sec.yaml
- hpa.yaml
- configmap.yaml
- ingress.yaml
- ../../../base/apps/forge_patient_frontend

patchesStrategicMerge:
- deploy.yaml

images:
- name: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/forge-patient-frontend-develop
  newTag: '5'
