apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-authentication-develop
  labels:
    app: forge-authentication-develop
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: forge-authentication-develop
  template:
    metadata:
      labels:
        app: forge-authentication-develop
    spec:
      # serviceAccountName: forge-authentication-develop-sa
      containers:
        - name: forge-authentication
          image: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/forge-authentication-develop
          envFrom:
            - configMapRef:
                name: forge-authentication-env-cm
            - secretRef:
                name: forge-authentication-env-sec
            - secretRef:
                name: devdb-password
          ports:
            - containerPort: 9000
              name: http-assessment                     
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "curl localhost:9000/"
            initialDelaySeconds: 300
            periodSeconds: 15
            successThreshold: 1
      #     volumeMounts:
      #       - name: assessment-aws-secrets
      #         mountPath: "/mnt/secrets"
      #         readOnly: true
      #     env:
      #     - name: Assessment_CREDS
      #       valueFrom:
      #         secretKeyRef:
      #           name: "assessment-creds-sec" 
      #           key: assessment-creds
      # volumes:
      #   - name: assessment-aws-secrets
      #     csi: 
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "assessment-aws-secrets"
