apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-backend-staging
  labels:
    app: saleor-backend-staging
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: saleor-backend-staging
  template:
    metadata:
      labels:
        app: saleor-backend-staging
    spec:
    # serviceAccountName: stg-saleor-backend-sa
      containers:
        - name: saleor-backend
          image: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/saleor-backend-staging
          envFrom:
            - configMapRef:
                name: saleor-backend-env-cm
            - secretRef:
                name: saleor-backend-env-sec
          ports:
            - containerPort: 8000
              name: http-saleor                   
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          command: ['/bin/bash', '-c', 'chmod +x ./scripts/api.sh; ./scripts/api.sh;']
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "curl localhost:8000/graphql/"
            initialDelaySeconds: 210
            periodSeconds: 15
            successThreshold: 1
#          volumeMounts:
#            - name: saleor-aws-secrets
#              mountPath: "/mnt/secrets"
#              readOnly: true
#          env:
#          - name: Saleor_CREDS
#            valueFrom:
#              secretKeyRef:
#                name: "saleor-creds-sec" 
#                key: saleor-creds
#      volumes:
#        - name: saleor-aws-secrets
#          csi: 
#            driver: secrets-store.csi.k8s.io
#            readOnly: true
#            volumeAttributes:
#              secretProviderClass: "saleor-aws-secrets"
