apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis-service.yaml
- redis-pv.yaml
- redis-pvc.yaml
- redis-statefulset.yaml
- deploy.yaml
- service.yaml

commonLabels:
  app_svc: saleor-backend-staging
