apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None  # Headless service, which allows DNS resolution of individual pods
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
