apiVersion: v1
kind: ConfigMap
metadata:
  name: assessment-api-env-cm
data:
  NODE_ENV: development
  DB_HOST: forge-qa.c3eewy88e76c.eu-west-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: assessments
  DB_USERNAME: forgeqa
  DB_PASSWORD: Xem6lbtf0c2A3DNUmk06
  DB_DIALECT: postgres
  HOST: localhost
  PORT: "9000"
  SWAGGER_UNAME: forge-assessment-admin
  SWAGGER_PASSWORD: "forge-assessment-admin-12345"
  BASE_URL_MISCELLANEOUS_SYSTEM: https://global-api-stg.simpleonlinehealthcare.co.uk/api
  MAX_QUESTION_LEVEL: "5"
  MAX_QUESTION_CHILDREN: "5"
