apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: assessment-api-qa
  namespace: argocd
spec:
  project: sop-qa
  source:
    repoURL: 'https://github.com/Simple-Online-Healthcare/forge_k8s_manifests.git'
    path: deployments/apps/assessment_api
    targetRevision: deploy-qa
    directory:
      recurse: false
      jsonnet: {}
  destination:
    namespace: assessment-api-qa
    name: forge-qa
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true    
    syncOptions:
      - CreateNamespace=true
