apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-celery-flower-staging
  labels:
    app: saleor-celery-flower-staging
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: saleor-celery-flower-staging
  template:
    metadata:
      labels:
        app: saleor-celery-flower-staging
    spec:
      containers:
        - name: celery-flower
          image: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/saleor-celery-staging:latest
          env: 
            - name: ISFLOWER 
              value: 'true'
            - name: ISFLOWERAUTH
              value: 'true'
            
          envFrom:
            - configMapRef:
                name: saleor-celery-env-cm
            - secretRef:
                name: saleor-celery-env-sec
          ports:
            - containerPort: 5566
              name: http-flower         
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "1024Mi"
          command: ['/bin/bash', '-c', 'chmod +x ./scripts/celery.sh; ./scripts/celery.sh;']
