apiVersion: v1
kind: ConfigMap
metadata:
  name: saleor-celery-env-cm
data:
  NODE_ENV: DEVELOPMENT
  #AWS_DEFAULT_ACL: ""
  #AWS_MEDIA_BUCKET_NAME: forge-saleor-dev
  #AWS_MEDIA_CUSTOM_DOMAIN: ""
  #AWS_MEDIA_PRIVATE_BUCKET_NAME: forge-saleor-dev
  #AWS_QUERYSTRING_AUTH: ""
  #AWS_QUERYSTRING_EXPIRE: ""
  #AWS_STATIC_CUSTOM_DOMAIN: ""
  #AWS_STORAGE_BUCKET_NAME: forge-saleor-dev
