apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saleor-backend-staging

commonLabels:
  customer: saleor-celery-staging
resources:
- sec.yaml
- configmap.yaml
- celery-flower-deploy.yaml
- flower-service.yaml
- celery-beat-deploy.yaml
- beat-service.yaml
- flower-ingress.yaml
- hpa.yaml
- ../../../base/apps/celery-backend

patchesStrategicMerge:
- deploy.yaml


images:
- name: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/saleor-celery-staging
  newTag: '1'
