apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saleor-celery-staging
  namespace: argocd
spec:
  project: sop-staging
  source:
    repoURL: 'https://github.com/Simple-Online-Healthcare/forge_k8s_manifests.git'
    path: deployments/apps/celery-backend
    targetRevision: deploy-staging
    directory:
      recurse: false
      jsonnet: {}
  destination:
    namespace: saleor-backend-staging
    name: forge-staging
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true    
    syncOptions:
      - CreateNamespace=true
