apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forge-miscellaneous-develop

commonLabels:
  customer: forge-miscellaneous-develop
resources:
- sec.yaml
- hpa.yaml
- configmap.yaml
- ingress.yaml
- ../../../base/apps/forge_miscellaneous

patchesStrategicMerge:
- deploy.yaml

images:
- name: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/forge-miscellaneous-develop
  newTag: '7'