apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: assessment-patient-api-qa

commonLabels:
  customer: assessment-patient-api-qa
resources:
- sec.yaml
- api-aws-sec.yaml
- hpa.yaml
- configmap.yaml
- ingress.yaml
- ../../../base/apps/assessment_patient_api

patchesStrategicMerge:
- deploy.yaml

images:
- name: 476114148868.dkr.ecr.eu-west-2.amazonaws.com/assessment-patient-api-qa
  newTag: '1'
